### ISSUE TITLE
Issues when opening the solutions

### ISSUE THREAD

**Issue by helloitsm3** [mehrandvd/LumberRacer#1]
I'm having issues when I try to compile the project. Do I need to download anything? I got a lot of errors when I try to compile

**Comment by mehrandvd** [comment]
The project has nothing required to compile.
Can you explain more about your compiling error.

**Comment by helloitsm3** [comment]
I downloaded your source code, but when I open LumberRacer.sln with visual studio 2013, I have errors. 
![untitled](https://cloud.githubusercontent.com/assets/13825491/20459826/4e06618e-af0b-11e6-85dc-bc388c272c02.png)

**Comment by mehrandvd** [comment]
Aha, I see, I use C# 6.0, so you need to open the project with Visual Studio 2015.
The error lines shows where I used new features in C# 6.0 like property initializers.

**Comment by helloitsm3** [comment]
I see. Thanks
